blank_issues_enabled: false
contact_links:
  - name: ğŸ”§ OpenList æ–‡æ¡£
    url: https://docs.oplist.org/
    about: åº•å±‚æœåŠ¡çš„å®˜æ–¹ OpenList æ–‡æ¡£
  - name: ğŸŒ Rclone æ–‡æ¡£
    url: https://rclone.org/docs/
    about: è¿œç¨‹å­˜å‚¨é…ç½®çš„å®˜æ–¹ Rclone æ–‡æ¡£
